### ISSUE TITLE
Point mirroring of the generated QR codes

### ISSUE THREAD

**Issue by sherrnleben** [hprid/reportlab-qrcode#1]
We are using your library within some ReportLab projects to generate QR codes. We have noticed some strange behavior today: Some of our barcode readers are not able to decode the generated QR codes. We experimented a lot, however, we were not able to find a suitable barcode scanner configuration to read the generated QR codes.

We then analyzed the generated codes with the following site: https://qrlogo.kaarposoft.dk/qrdecode.html
On this site, we always got the error message "uncaught exception: Unable to correct errors (corrections out of scope)" for all QR codes generated (or better drawn) by your library. To get an idea of what's going wrong, we created a code with the [qrcode](https://pypi.org/project/qrcode/) library directly. The QR codes directly generated by the qrcode library looked different, and our barcode scanners could read them.

After a long investigation, we found that your library apparently applies point mirroring to the generated QR codes. Some "more intelligent" barcode readers might be able to decode the point-mirrored codes, but some other barcode readers can't.

In the following, we show the QR code generated by your [simple example script](https://github.com/hprid/reportlab-qrcode/blob/master/examples/simple.py):

<img width="136" alt="qr-mirrored" src="https://github.com/hprid/reportlab-qrcode/assets/11692196/a09c8ad4-a6d4-4ebc-9782-b5ea3faf94df">

When creating the QR code with the same parameters as the qrcode library directly, we get the following output:

<img width="135" alt="qr-ok" src="https://github.com/hprid/reportlab-qrcode/assets/11692196/fe6203a2-b25d-4f31-9ffa-25f65a36a92e">

In my opinion, there is an error in your `draw` method in [line 46](https://github.com/hprid/reportlab-qrcode/blob/master/reportlab_qrcode/__init__.py#L46). When replacing the statement 
```py
xr, yr = yr, -xr
```
by 
```py
yr = -yr
```
the codes are output correctly, and all of our barcode scanners and the above-mentioned debug internet site can decode them.

Please consider applying our suggested bugfix.

**Comment by hprid** [comment]
Thank you for the detailed bug report. I have uploaded a new release to PyPi.

**Comment by sherrnleben** [comment]
@hprid Thanks a lot for the very quick bugfix and the new release.
